name: Mensagens personalizadas com Python

on:
 schedule:
  - cron: '0 3 * * 3'
 workflow_dispatch:

jobs:
  run-script: 
   runs-on: ubuntu-24.04
   permissions:
    contents: write
   steps:
    - name: Check do código
      uses: actions/checkout@v4
   
    - name: Configurando python na VM
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Executando script de atualização
      run: python update_insight.py

    - name: Salvar e commitar alterações no README
      run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bot: Update insight do dia via Python" || echo "Sem alterações"
          git push
  
